Repository danbilokha/covid19liveupdates, pull requests merged in 2020-04, with the labels that each got.

#46 UI\UX improvements
  server/src/bots/telegram/botResponse/adviceResponse.ts
  server/src/bots/telegram/botResponse/assistantResponse.ts
  server/src/bots/telegram/botResponse/availableResponse.ts
  server/src/bots/telegram/botResponse/countriesResponse.ts
  server/src/bots/telegram/botResponse/countryResponse.ts
  server/src/bots/telegram/botResponse/helpResponse.ts
  server/src/bots/telegram/botResponse/startResponse.ts
  server/src/bots/telegram/index.ts
  server/src/bots/telegram/utils/keyboard.ts
  server/src/environments/environment.ts
  server/src/messages/covid19Messages.ts
  server/src/messages/feature/assistantMessages.ts
  server/src/messages/feature/availableMessages.ts
  server/src/messages/feature/countriesMessages.ts
  server/src/messages/feature/countryMessages.ts
  server/src/messages/feature/helpMessages.ts
  server/src/messages/userMessage.ts
  server/src/models/constants.ts
  server/src/services/api/api-knowledgebase.ts
  server/src/services/domain/covid19.ts
  server/src/utils/cache.ts
  server/src/utils/featureHelpers/country.ts
  server/src/utils/incomingMessage.ts
  server/src/utils/incomingMessages.ts
  server/src/utils/logger.ts
Labels: enhancement

#76 fix url, sending just picture now
  server/src/bots/telegram/botResponse/trendResponse.ts
Labels: bug

#83 add user to firebase db on start command
  server/src/bots/telegram/botResponse/assistantResponse.ts
  server/src/bots/telegram/botResponse/countryResponse.ts
  server/src/bots/telegram/botResponse/noResponse.ts
  server/src/bots/telegram/botResponse/startResponse.ts
  server/src/bots/telegram/botResponse/trendResponse.ts
  server/src/bots/telegram/index.ts
  server/src/bots/telegram/services/messageHandlerRegistry.ts
  server/src/bots/telegram/services/storage.ts
  server/src/bots/telegram/services/subscriptionNotifierManager.ts
  server/src/messages/feature/assistantMessages.ts
  server/src/models/constants.ts
  server/src/models/loggly.models.ts
  server/src/models/user.model.ts
  server/src/services/domain/countries.ts
  server/src/services/domain/covid19.ts
  server/src/services/domain/storage.ts
  server/src/services/infrastructure/scheduler.ts
  server/src/utils/getErrorMessages.ts
  server/src/utils/logger.ts
Labels: Feature request, good first issue

#90 send scheduled notifications for user
  server/src/bots/telegram/botResponse/startResponse.ts
  server/src/bots/telegram/index.ts
  server/src/bots/telegram/services/storage.ts
  server/src/environments/environment.ts
  server/src/models/constants.ts
  server/src/models/user.model.ts
  server/src/services/domain/storage.ts
  server/src/services/infrastructure/scheduler.ts
  server/src/utils/user.utils.ts
Labels: enhancement

#91 Improve charts partially resolves #80
  server/src/bots/telegram/botResponse/trendResponse.ts
  server/src/bots/telegram/index.ts
  server/src/bots/telegram/services/keyboard.ts
  server/src/bots/telegram/services/registry/withTwoArgumentsAfterCommand.ts
  server/src/models/chart.models.ts
  server/src/models/constants.ts
  server/src/services/domain/chart.ts
  server/src/utils/dateUtils.ts
Labels: enhancement

#92 refactor storage
  server/src/bots/telegram/botResponse/startResponse.ts
  server/src/bots/telegram/botResponse/subscribeResponse.ts
  server/src/bots/telegram/botResponse/unsubscribeResponse.ts
  server/src/bots/telegram/services/storage.ts
  server/src/bots/telegram/services/subscriptionNotifierManager.ts
  server/src/models/user.model.ts
  server/src/services/domain/storage.ts
  server/src/services/domain/subscriptions.ts
  server/src/services/infrastructure/scheduler.ts
  server/src/utils/user.utils.ts
Labels: enhancement
